### ISSUE TITLE
[Enhancement] Redstone Compatability

### ISSUE THREAD

**Issue by milkev** [tratteo/LiterallyChunkLoader-1.15#4]
It would be cool if the chunk loader could be controlled automatically via redstone.
Example:
When recieving a redstone signal, the chunk loader is activated, when the chunk loader loses a redstone signal, its deactivated.

This would make it so you could wire up multiple to be turned on/off from one place, and combined with mods with redstone logic, can be used to have these chunks deactivate when a certain condition is met. (ie: create a crop farm using ticktock, and when the chests are full, use a comparator to cut the redstone signal to the chunk loader, causing it to deactivate and the chunks to be unloaded)

of course you wouldnt be able to re-enable them remotely, but thats just a consequence of the chunks not being loaded in the first place.

**Comment by tratteo** [comment]
Thanks for the suggestion!
