### ISSUE TITLE
[Bug Report] If the Chunk Loader is destroyed by an explosion, the player is unable to place another Chunk Loader in that location. (Version 1.16-2.0.1)

### ISSUE THREAD

**Issue by LunaEversor** [tratteo/LiterallyChunkLoader-1.15#5]
I believe that I may have found a bug with the Chunk Loader. If the Chunk Loader is destroyed through an explosion, Creeper or TNT, the player will be unable to place another Chunk Loader at that location. The "/forceload remove all" command will reset the loaded chunk, however, it will not reset the players ability to place another Chunk Loader.

**Comment by tratteo** [comment]
Thanks, i'll look into it

**Comment by tratteo** [comment]
Fixed in 2.0.2
